# NumPy 

NumPy atau Numpy adalah library aljabar linear untuk Python. Hampir semua library di PyData ekosistem menjadikan NumPy sebagai salah satu dari bangunan utamanya.

Informasi tambahan dapat dilihat di website berikut [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Kita hanya akan belajar dasar-dasar NumPy, mari kita mulai dengan menginstal package ini terlebih dahulu.


## Cara Instalasi

**Sangat direkomendasikan untuk menginstal Python menggunakan Anaconda distribution untuk menjamin banyak package dasar sudah terinstal. Jika kamu menggunakan Anaconda, NumPy biasanya sudah terinstal. Jika belum, instalasi dapat dilakukan di command promp:**
    
    conda install numpy
    
**Jika proses instalasi gagal, silakan menuju ke halaman berikut [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Menggunakan NumPy

Jika sudah diinstal, silakan import Numpy sebagai sebuah library:

In [1]:
import numpy as np

Numpy memiliki banyak built-in function dan kapabilitas. Kita gak akan bahas semuanya. Pembahasan difokusin di bagian-bagian yang penting seperti: vectors, arrays, matrices, dan number generation. Yuk dimulai dari arrays.


# Numpy Arrays

NumPy arrays adalah bagian penting dari NumPy. Terdapat dua bentuk: vektor dan matriks. Vektor berbentuk 1-d arrays dan matriks terdiri dari 2-d (meski kita paham, matriks dapat juga berisi satu baris atau satu kolom).

Ni lho bentuknya.

## Membuat NumPy Arrays

### Dari sebuah Python List

Kita dapat mencipatakan sebuah array langsung dengan mengkonversi sebuah list atau list dari list:


In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [4]:
my_matriks = [[1,2,3],[4,5,6],[7,8,9]]
my_matriks

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matriks)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

Terdapat banyak built-in untuk menggenerate Arrays

### arange

Memanggil semua nilai yang terletak diantara interval.


In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Menggenerate arrays kosong dan satu.


In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Memanggil semua nilai berjarak sama sebanyak bilangan yang diberikan pada rentang interval tertentu.


In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Membuat sebuah matriks identitas.


In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy juga memiliki banyak cara untuk membuat array bilangan acak:


### rand

Membuat sebuah array dari shape yang diberikan dan membuatnya dengan sampel acak dari sebuah distribusi uniform dari 
``[0, 1)``.

In [17]:
np.random.rand(2)

array([0.17781605, 0.94197838])

In [18]:
np.random.rand(5,5)

array([[0.80803753, 0.27327078, 0.65053988, 0.74245844, 0.79303965],
       [0.75449566, 0.82717186, 0.16421625, 0.52827926, 0.40941533],
       [0.60557804, 0.97157142, 0.6605321 , 0.56307622, 0.03802594],
       [0.0167366 , 0.14620315, 0.68136283, 0.07648179, 0.07219606],
       [0.27858121, 0.1049054 , 0.52973433, 0.59247972, 0.13384695]])

### randn

Memanggil sampel dari sebuah standard normal distribution. Berbeda dengan rand.


In [19]:
np.random.randn(2)

array([0.50085043, 0.54577377])

In [21]:
np.random.randn(5,5)

array([[-0.80526918, -0.91356659,  0.57106708,  0.0247421 ,  1.17509213],
       [-0.29591104, -0.81874397, -1.73552959, -1.09088833, -0.91197279],
       [ 0.77234085,  0.11121521,  1.01628334,  0.03007134,  0.04893746],
       [-0.25029509, -0.18036914,  0.57428372, -0.61104026, -0.33550078],
       [ 0.55607666, -0.17551044,  0.97862389, -0.64553122, -1.52344727]])

### randint

Memanggil bilangan bulat secara acak dari `rendah` ke `tinggi`.


In [22]:
np.random.randint(1,100)

45

In [23]:
np.random.randint(1,100,10)

array([48, 66, 51,  3, 22, 89, 99, 97,  4, 13])

## Array Attributes and Methods

Ayo diskusi beberapa attributes dan metode yang berguna:



In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([35, 18, 41, 32,  4, 31,  6, 17, 32,  5])

## Reshape

Memanggil sebuah array yang memuat data yang sama namun bentuk yang berbeda.


In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Alat ini sangat berguna untuk mendapat nilai maksimum atau minimum. Atau untuk mendapatkan indeks lokasi menggunakan argmin atau argmax.


In [28]:
ranarr

array([35, 18, 41, 32,  4, 31,  6, 17, 32,  5])

In [29]:
ranarr.max()

41

In [30]:
ranarr.argmax()

2

In [31]:
ranarr.min()

4

In [32]:
ranarr.argmin()

4

## Shape

Shape adalah sebuah atrribute yang dimiliki arrays (bukan metode):

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Kita dapat juga mendapatkan tipe data dari sebuah obyek yang termuat dalam array:

In [38]:
arr.dtype

dtype('int32')

# Mantaps!