___
# NumPy Indexing dan Selection

Di notebook ini akan dituliskan bagaiman memilih elemen atau sekumpulan elemen dari sebuah array.

In [1]:
import numpy as np

In [2]:
#Membuat sebuah array
arr = np.arange(0,11)

In [3]:
#Menampilkan
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing dan Selection

Cara paling sederhana untuk memanggil satu atau beberapa elemen dari sebuah array mirip dengan cara yang digunakan di python list:

In [8]:
#Mengambil sebuah nilai pada sebuah index
arr[8]

8

In [9]:
#Mendapatkan nilai dari sebuah range
arr[1:5]

array([100, 100, 100, 100])

In [10]:
#Mendapatkan nilai dari sebuah range
arr[0:5]

array([100, 100, 100, 100, 100])

## Broadcasting

Numpy arrays berbeda dari sebuah Python list biasa karena kemampuannya untuk broadcast:

In [11]:
#Mengatur sebuah nilai dengan index range.(Broadcasting)
arr[0:5]=100

#Menampilkan
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
# Mengatur ulang array
arr = np.arange(0,11)

#Menampilkan
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Melakukan slices
slice_of_arr = arr[0:6]

#Menampilkan slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
#Mengubah Slice
slice_of_arr[:]=99

#Menampilkan Slice
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Perubahan ini juga mengubah array aslinya.

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data tidak dicopi, tapi menampilkan array yang asli! Hal ini menghindari masalah pada memori.

In [17]:
#Untuk mengcopi, harus dilakukan dengan eksplisit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

Format umumnya adalah **arr_2d[row][col]** or **arr_2d[row,col]**. Saya merekomendasikan biasanya menggunakan notasi koma supaya lebih jelas.

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Menampilkan
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
#Indexing baris
arr_2d[1]


array([20, 25, 30])

In [20]:
# Formatnya adalah arr_2d[row][col] or arr_2d[row,col]

# Memanggil elemen tertentu
arr_2d[1][0]

20

In [17]:
# Memanggil elemen tertentu
arr_2d[1,0]

20

In [21]:
# 2D array slicing

#Membentuk (2,2) dari pojok kanan atas
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [22]:
#Membentuk baris bawah
arr_2d[2]

array([35, 40, 45])

In [23]:
#Membentuk baris bawah
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing mengijinkan kita untuk memilih keseluruhan baris atau kolom diluar urutan, yuk dilihat:

In [24]:
#Mengatur matriks
arr2d = np.zeros((10,10))

In [25]:
#Panjang dari sebuah array
arr_length = arr2d.shape[1]
arr_length

10

In [26]:
#Mengatur array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing tu kek gini gengs

In [27]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [28]:
#Berlaku di setiap urutan
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

##  Indexing yang lain
Mengindeks sebuah 2d matriks dapat sedikit membingungkan, khususnya ketika baru mulai. 

## Selection

Ayo belajar menggunakan brackets untuk memilih berdasarkan komparasi operator.

In [29]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Mantaps!
